export default {
  user: {
    loggedIn: false,
    data: null,
  },
  newItem: "",
  todo: [],
  todoName: "Todo List",
  todoListID: "",
  tempID: "",
  title: "",
  titleColor: "#313639",
  newTitleColor: "",
  currentTime: "",
  editDialog: false,
  uploadImage: false,
  existingList: false,
  loading: false,
  saving: false,
  colorPickerDialog: false,
  notEditing: true,
  infoPanel: true,
  editItem: false,
  accountPanel: false,
  forgotDialog: false,
  sentDialog: false,
  paymentDialog: false,
  savedLinks: [],
  rules: {
    required: (value) => !!value || "Required.",
    counterMin3: (value) =>
      value.length >= 3 || "Your list name has to have at least 3 characters",
    counterMax25: (value) =>
      value.length <= 25 || "Your list name can only be up to 25 characters",
  },
};
